apiVersion: apps/v1
kind: Deployment
metadata:
  name: nf-web
spec:
  selector:
    matchLabels:
      app: nf-web
  replicas: 1
  template:
    metadata:
      name: nf-web
      labels:
        app: nf-web
    spec:
      containers:
      - image: quay.io/cellgeni/nf-web:latest
        imagePullPolicy: Always
        name: nf-web
        ports:
        - containerPort: 8000
          hostPort: 18045
          name: nf-web
        resources:
          requests:
            memory: "128Mi"
            cpu: 100m
          limits:
            memory: "1Gi"
            cpu: 1
        env:
          - name: PROCESSING_HOST
            value: http://nfweb-backend.cellgeni.sanger.ac.uk:9992
          - name: ODDJOB_HOST
            value: http://nfweb-backend.cellgeni.sanger.ac.uk:9999
#        livenessProbe:
#          httpGet:
#            path: /nf-web
#            port: nf-web
#          initialDelaySeconds: 10
#          timeoutSeconds: 5
#          periodSeconds: 240
