apiVersion: apps/v1
kind: Deployment
metadata:
  name: nf-web
spec:
  selector:
    matchLabels:
      app: nf-web
  replicas: 1
  template:
    metadata:
      name: nf-web
      labels:
        app: nf-web
    spec:
      containers:
      - image: quay.io/cellgeni/mprofile-web:v0.1.12
        imagePullPolicy: IfNotPresent
        name: nf-web
        ports:
        - containerPort: 8005
          hostPort: 8005
          name: nf-web
        resources:
          requests:
            memory: "512Mi"
            cpu: 1
          limits:
            memory: "2Gi"
            cpu: 2
        env:
          - name: MODEL_HOST
            value: http://predictor.default.svc.cluster.local
        livenessProbe:
          httpGet:
            path: /nf-web
            port: nf-web
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 240
